package com.huawei.ibc.model.common;

public enum NodeType {

    COMPUTE_NODE, SWITCH, ROUTER, FIREWALL, GATEWAY, NAT, APPLICATION, INTERNET, SUBNET, ACL, LB, GROUP, POLICY, POLICY_ALLOW, POLICY_DENY, SERVICE;

}
